---
title: "PSTAT 174/274 Spring 2023: Homework 7"
author: "Dylan Berneman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1
Time series {X~t~} follows stationary AR(1) model X~t~ = $\phi_0$ + $\phi_1$X~t−1~ + Z~t~, Z~t~ ∼ N(0, σ~Z~^2^). Determine which of the following statements about this model is false.\

  (A) the parameter $\phi_0$ must not equal 1.\
    *- FALSE. The parameter $\phi_0$ is a constant that only affects the value of the mean of the AR(1) model. For a stationary process its mean does not depend on time, i.e., a constant.*\
  
  (B) The absolute value of the parameter $\phi_1$ must be less than 1.\
    *- TRUE. In order to remain stationary, the coefficients of an AR(p) model must all have absolute values lower than 1, otherwise to ensure that the roots are outside of the unit circle.*\
  
  (C) If the parameter $\phi_1$ = 0, then the model reduces to a white noise process.\
    *- TRUE. If $\phi_1=0$, then the equation of the model is simplified to $X_t=\phi_0+Z_t$ where $\phi_0$ is the drift.*\
  
  (D) If the parameter $\phi_1$ = 1, then the model is a random walk.\
    *- TRUE. If $\phi_1$ = 1, then the model can be simplified to a random walk with a drift of $\phi_0$.*\
  
  (E) Only the immediate past value X~t−1~, is used as a predictor for X~t~.\
    *- TRUE*\
\
  
### Question 2
(Updating forecasts) You use AR(1) model X~t~ − 100 = 0.6(X~t−1~ − 100) + Z~t~ to represent a time series of 100 observations. You are given that X~100~ = 110. You later observe X~101~ = 95. Calculate P~101~X~103~ − P~100~X~103~.\
*(Hint: review Example 13.1 on slides 9 - 10 of Week 7.)*\

$$
\begin{aligned}
&\text{For general h: } P_nX_{n+h} = \phi_1^hX_n\\
\phi_1 &= 0.6;\ \ \ \ X_{100}=110;\ \ \ \ X_{101}=95;\\\
&\text{Calculate }P_{101}X_{103}-P_{100}X_{103}\\\\
\text{First, solve for }& P_{101}X_{103}:\\
P_{101}X_{103} & = P_{101}X_{101+2}\\
&= \phi_1^2\ X_{101}\\
&=100+0.6^2(95-100)\\
&=98.2\\\\
\text{Next, solve for }& P_{100}X_{103}:\\
P_{100}X_{103} & = P_{100}X_{100+3}\\
&= \phi_1^3\ X_{100}\\
&=100+0.6^3(110-100)\\
&=10+0.216(10)\\
&=102.16\\\\
P_{101}X_{103}-P_{100}X_{103} & = 102.16-98.2\\
&=3.96
\end{aligned}
$$
\
\

### Question 3
You are given the AR(3) model for X~t~, a company’s revenue for year t: X~t~ = 5 + 0.85X~t−1~ −0.02X~t−3~ +Z~t~, Z~t~∼WN(0,σ^2^). The revenues for the last 4 years are as follows:\

| Year | Revenue |
|:----:|:-------:|
| 2019 | 20 |
| 2020 | 15 |
| 2021 | 22 |
| 2022 | 19 |

Forecast the expected revenue for 2024. *(Hint: review Example 13.2 of week 7, slide 11.)*\
\
$$
\begin{aligned}
X_t = 5 + & 0.85X_{t-1}-0.02X_{t-3}+Z_t\\\\
P_nX_{n+1} &= E_n[X_{n+1}]\\
P_{2022}X_{2023} &= E_{2022}[X_{2023}]\\
& = E[5 + \phi_1X_{t-1}+\phi_2X_{t-3} +Z_{t}]\\
& = E[5 + \phi_1X_{2022}+\phi_2X_{2020} +Z_{2022}]\\
&= 5 + \phi_1X_{2022}+\phi_2X_{2020}\\
&= 5 + 0.85(19)-0.02(15) + 0\\
&= 20.85\\\\
P_nX_{n+2} &= E_n[X_{n+2}]\\
P_{2022}X_{2024} &= E_{2022}[X_{2024}]\\
& = E[5 + \phi_1X_{t-1}+\phi_2X_{t-3} +Z_{t}]\\
& = E[5 + \phi_1X_{2023}+\phi_2X_{2021} +Z_{2023}]\\
&= 5 + \phi_1X_{2022}+\phi_2X_{2020}\\
&= 5 + 0.85(20.85)-0.02(22) + 0\\
&= 22.2825
\end{aligned}
$$
\
\

### Question 4
A Gaussian AR(1) model was fitted to a time series based on a sample of size n. You are given
$\hat{\phi}_1$ = 0.8, $\hat{\mu}$ = 2, $\hat{\sigma}^2_Z$ = 9 × 10^−4^, x~n~ = 2.05. Write the 95% prediction interval for the observation three periods ahead.\

*Hint: review Example 13.1 of Week 7; slide 10. Do not forget that the mean is not 0!*\

$$
\begin{aligned}
\text{Given: }& \hat{\phi}_1 = 0.8,\ \ \ \hat{\mu} = 2,\ \ \ \hat{\sigma}^2_Z = 9 × 10^{−4},\ \ \ x_n = 2.05\\
\text{Calculate the 95% prediction} & \text{ interval for the observation three periods ahead}\\
P_nX_{n+h}\ &\pm\ 1.96 \sqrt{Var(e_n(h))}\\\\
P_nX_{n+h} &= P_nX_{n+3}\\
&=\hat{\mu}+\phi_1^3X_n \\
&= 2+0.8^3  * 2.05\\
&=3.0496
\end{aligned}
$$
\
$$
\begin{aligned}
Var(e_n(h)) &= \sigma^2_Z(1-\phi_1^{2h})/(1-\phi_1^2)\\
Var(e_n(3)) &= \sigma^2_Z(1-\phi_1^{2(3)})/(1-\phi_1^2)\\
&=9*10^{-4}\ (1-\phi_1^6)/(1-\phi_1^2)\\
&=9*10^{-4}\ (1-0.8^6)/(1-0.8^2)\\
&= 0.0065536\\
\sqrt{Var(e_n(3))} &= \sqrt{0.0065536}\\
&=0.0256
\end{aligned}
$$
\
$$
\begin{aligned}
& \ \ \ \ \ P_nX_{n+h}\ \pm\ 1.96 \sqrt{Var(e_n(h))}\\
&=(3.0496\ \pm\ 1.96(0.0256))\\
&= (3.0496\ \pm\ 0.050176)\\
&=(2.999, \ 3.10 )
\end{aligned}
$$
\

**The following problem is for students enrolled in PSTAT 274 ONLY**\

### Question G1
A Gaussian AR(1) model was fitted to a time series based on a sample of size n = 51. You are given: $\hat{\mu}$  = 16.75, $\hat{\phi}_1$ = 0.75. The last observation was x~51~ = 20.25, and the sum of the squares of the 51 residuals is 75.7. Determine the upper bound of the shortest 95% probability limit for the forecast of the observation two time periods ahead.\

$$
\begin{aligned}
\text{Given:  } &n=51,\ \ \ \ forecast=2\ ahead,\ \ \ \ \hat{\mu}=16.75,\ \ \ \ \hat{\phi}_1=0.75,\ \ \ \ x_{51}=20.25,\ \ \ \ SSR=75.7\\
Find\ & \ \ \ \ P_nX_{n+h}\ \pm\ 1.96 \sqrt{Var(e_n(h))}\\\\
\hat{\sigma}^2_X &= RSS/(n-2)\\
&= 75.7/49\\
&=1.545\\\\
P_nX_{n+h} &= P_nX_{n+2}\\
&=\hat{\mu}+P_{51}X_{51+2}\\
&=\hat{\mu}+\phi_1^2X_{51} \\
&= 16.75+0.75^2  * 20.25\\
&=28.141\\\\
Var(e_n(h)) &= \sigma^2_Z(1-\phi_1^{2h})/(1-\phi_1^2)\\
Var(e_n(3)) &= \sigma^2_Z(1-\phi_1^{2(2)})/(1-\phi_1^2)\\
&=1.545\ (1-\phi_1^4)/(1-\phi_1^2)\\
&=1.545\ (1-0.75^4)/(1-0.75^2)\\
&= 2.414\\
\sqrt{Var(e_n(3))} &= \sqrt{2.414}\\
&=1.554
\end{aligned}
$$
\
$$
\begin{aligned}
& \ \ \ \ \ P_nX_{n+h}\ \pm\ 1.96 \sqrt{Var(e_n(h))}\\
&=(3.0496\ \pm\ 1.96(1.554))\\
&= (3.0496\ \pm\ 2.0452)\\
&=(25.095, \ 31.186 )
\end{aligned}
$$
