---
title: "Project"
author: "Dylan Berneman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages('astsa')
install.packages('tseries')
install.packages('basicTrendline')
install.packages("nortsTest")
install.packages("nortest")
install.packages('distributional')
install.packages("TSA")
install.packages('FinTS')
install.packages('FitAR')
install.packages("forecast")
install.packages('ggplot2')
install.packages("ggfortify")
install.packages('latex2exp')
install.packages('polynom')
install.packages('sarima')
install.packages("MuMIn")
devtools::install_github("FinYang/tsdl")
library(devtools)
library(tseries)
library(nortsTest)
library(nortest)
library(TSA)
library(MuMIn)
library(astsa)
library(basicTrendline)
library(tsdl)
library(dplyr)
library(FinTS)
library(FitAR)
library(forecast)
library(ggplot2)
library(latex2exp)
library(ggfortify)
library(MASS)
library(polynom)
library(readr)
library(readxl)
library(sarima)
library(tinytex)

```

# Original Dataset
```{r}
options(scipen = 9)
covid <- read_excel("World_Covid.xlsx")
# covid <- read.csv("owid-covid-data 2.csv")
# covid = read.csv("Covid.csv")
# 
# vect=vector()
# for(i in 1:175){
#   vect=append(vect, rep(i, 7))
# }
# covid=covid[1:1225,]
# covid$Week = vect

# covid <- covid %>%
#   group_by(date) %>%
#   summarise(across(c(new_cases, new_deaths, population, people_vaccinated), sum))

# covid <- covid %>%
#   mutate("Mortality" = covid$new_deaths/covid$new_cases)


Mortality1 = ts(covid$Mortality[10:1238])
Mortality2 = ts(covid$Mortality[10:336])
Mortality3 = ts(covid$Mortality[337:1238])
Vaccinated1 = ts(covid$people_vaccinated[337:1238])
Death1 = ts(covid$new_deaths_smoothed[10:1238])
Death2 = ts(covid$new_deaths_smoothed[10:336])
Death3 = ts(covid$new_deaths_smoothed[337:1238])
Cases1 = ts(covid$new_cases_smoothed[6:1238])
Cases2 = ts(covid$new_cases_smoothed[6:336])
Cases3 = ts(covid$new_cases_smoothed[337:1238])

Mortality1= data.frame(Mortality1)
Mortality2= data.frame(Mortality2)
Mortality3= data.frame(Mortality3)
Vaccinated1= data.frame(Vaccinated1)
Death1= data.frame(Death1)
Death2= data.frame(Death2)
Death3= data.frame(Death3)
Cases1= data.frame(Cases1)
Cases2= data.frame(Cases2)
Cases3= data.frame(Cases3)

vect = vector()
vect = append(vect, Mortality1)
vect = append(vect, Mortality2)
vect = append(vect, Mortality3)
vect = append(vect, Vaccinated1)
vect = append(vect, Death1)
vect = append(vect, Death2)
vect = append(vect, Death3)
vect = append(vect, Cases1)
vect = append(vect, Cases2)
vect = append(vect, Cases3)


vect1 = vector()
vect1 = append(vect1, "Mortality1")
vect1 = append(vect1, "Mortality2")
vect1 = append(vect1, "Mortality3")
vect1 = append(vect1, "Vaccinated1")
vect1 = append(vect1, "Death1")
vect1 = append(vect1, "Death2")
vect1 = append(vect1, "Death3")
vect1 = append(vect1, "Cases1")
vect1 = append(vect1, "Cases2")
vect1 = append(vect1, "Cases3")
```
\
# Transformed Dataset
```{r}
# To choose parameter λ of the Box-Cox transformation for datset Mortality: 
for(i in 1:length(vect)){
  bcTransform <- boxcox(vect[[i]]~ as.numeric(1:length(vect[[i]])))       # plot the graph

  bcTransform$x[which(bcTransform$y == max(bcTransform$y))] # gives the value of λ
  lambda=bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
  title(main = paste0(vect1[i], "  lambda = ", round(lambda, 3)))
  
  # Perform transformations, plot transformed data, histograms:
  assign(paste0(vect1[i], ".bc"),  data.frame((1/lambda)*(vect[[i]]^lambda-1)))
  assign(paste0(vect1[i], ".log"),  data.frame(log(vect[[i]])))
  assign(paste0(vect1[i], ".sqrt"), data.frame(sqrt(vect[[i]])))
  
  transform = vector()
  transform = append(transform, data.frame(vect[[i]]))
  transform = append(transform, get(paste0(vect1[i], ".bc")))
  transform = append(transform, get(paste0(vect1[i], ".log")))
  transform = append(transform, get(paste0(vect1[i], ".sqrt")))

  assign(paste0("form_", vect1[i]), transform)
  

  transform_name = vector()
  transform_name = append(transform_name, vect1[i])
  transform_name = append(transform_name, paste0(vect1[i], ".bc"))
  transform_name = append(transform_name, paste0(vect1[i], ".log"))
  transform_name = append(transform_name, paste0(vect1[i], ".sqrt"))

    assign(paste0("name", vect1[i]), transform_name)
  
  for(j in 1:length(transform)){
    op <- par("mfrow", "mar")
    par(mfrow = c(2, 2), mar = c(rep.int(3, 3), 0.5))
    model=ets(transform[[j]])
    print(summary(model))
    x=acf2(transform[[j]], main=transform_name[j])
    mtext(paste0("Shapiro: p-value = ", signif(shapiro.test(transform[[j]])$p.value, digits=3), "     McLeod-Li: p-value = ", signif(Box.test((transform[[j]])^2, lag=sqrt(length(transform[[j]])), type=c("Ljung-Box"), fitdf = 0)$p.value, digits=3), "     ad.test: p-value = ", signif(ad.test(transform[[j]])$p.value, digits=3)), side=3, line=2.5, adj=1.375, cex=0.8)
    mtext(paste0("Box-Pierce: p-value = ", signif(Box.test(transform[[j]], lag = sqrt(length(transform[[j]])), type = c("Box-Pierce"), fitdf = 0)$p.value, digits=3),"     Ljung-Box: p-value = ", signif(Box.test(transform[[j]], lag=sqrt(length(transform[[j]])), type=c("Ljung-Box"), fitdf = 0)$p.value, digits=3), "     kpss.test: p-value = ", signif(kpss.test(transform[[j]])$p.value, digits=3)), side=3, line=1.5, adj=1.5, cex=0.8)
    require(TSA)
    # nf <- par(mfrow=c(2,2))
    plot.ts(transform[[j]], main=transform_name[j])
    abline(h=mean(transform[[j]]), col= "blue")
    abline(lm(transform[[j]] ~ as.numeric(1:length(transform[[j]]))), col="red")
    periodogram(transform[[j]], log = 'yes', main=paste0(transform_name[j], " Periodogram"))
    abline(h=0)
    hist(transform[[j]], col="light blue", xlab="", main=transform_name[j], prob=TRUE)
    m <- mean(transform[[j]])
    std <- sqrt(var(transform[[j]]))
    curve( dnorm(x,m,std), add=TRUE)
    qqnorm(transform[[j]],main= paste0(transform_name[j], " Q-Q Plot"))
    qqline(transform[[j]],col="blue")
    par(mfrow = op$mfrow, mar = op$mar)}}

# From looking at every histogram, none of the seem to fit a normal distribution. The following are the ones which are way off from being normal, and thus, will not test any further.
```

```{r}
for(i in 1:length(vect)){
  bcTransform <- boxcox(vect[[i]]~ as.numeric(1:length(vect[[i]])))       # plot the graph

  bcTransform$x[which(bcTransform$y == max(bcTransform$y))] # gives the value of λ
  lambda=bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
  title(main = paste0(vect1[i], "  lambda = ", round(lambda, 3)))
  
  # Perform transformations, plot transformed data, histograms:
  assign(paste0(vect1[i], ".bc"),  data.frame((1/lambda)*(vect[[i]]^lambda-1)))
  assign(paste0(vect1[i], ".log"),  data.frame(log(vect[[i]])))
  assign(paste0(vect1[i], ".sqrt"), data.frame(sqrt(vect[[i]])))
  
  transform = vector()
  transform = append(transform, data.frame(vect[[i]]))
  transform = append(transform, get(paste0(vect1[i], ".bc")))
  transform = append(transform, get(paste0(vect1[i], ".log")))
  transform = append(transform, get(paste0(vect1[i], ".sqrt")))

  assign(paste0("form_", vect1[i]), transform)
  

  transform_name = vector()
  transform_name = append(transform_name, vect1[i])
  transform_name = append(transform_name, paste0(vect1[i], ".bc"))
  transform_name = append(transform_name, paste0(vect1[i], ".log"))
  transform_name = append(transform_name, paste0(vect1[i], ".sqrt"))

    assign(paste0("name", vect1[i]), transform_name)
    
    op <- par("mfrow", "mar")
    par(mfrow = c(2, 2), mar = c(rep.int(3, 3), 0.5))
    for(j in 1:length(transform)){
      hist(transform[[j]], col="light blue", xlab="", main=transform_name[j], prob=TRUE)
      m <- mean(transform[[j]])
      std <- sqrt(var(transform[[j]]))
      curve( dnorm(x,m,std), add=TRUE)}
    par(mfrow = op$mfrow, mar = op$mar)}
```
fisher.g.test

```{r}

```

```{r}
for(i in 1:length(vect)){
  bcTransform <- boxcox(vect[[i]]~ as.numeric(1:length(vect[[i]])))       # plot the graph

  bcTransform$x[which(bcTransform$y == max(bcTransform$y))] # gives the value of λ
  lambda=bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
  title(main = paste0(vect1[i], "  lambda = ", round(lambda, 3)))
  
  # Perform transformations, plot transformed data, histograms:
  assign(paste0(vect1[i], ".bc"),  data.frame((1/lambda)*(vect[[i]]^lambda-1)))
  assign(paste0(vect1[i], ".log"),  data.frame(log(vect[[i]])))
  assign(paste0(vect1[i], ".sqrt"), data.frame(sqrt(vect[[i]])))
  
  transform = vector()
  transform = append(transform, data.frame(vect[[i]]))
  transform = append(transform, get(paste0(vect1[i], ".bc")))
  transform = append(transform, get(paste0(vect1[i], ".log")))
  transform = append(transform, get(paste0(vect1[i], ".sqrt")))

  assign(paste0("form_", vect1[i]), transform)
  

  transform_name = vector()
  transform_name = append(transform_name, vect1[i])
  transform_name = append(transform_name, paste0(vect1[i], ".bc"))
  transform_name = append(transform_name, paste0(vect1[i], ".log"))
  transform_name = append(transform_name, paste0(vect1[i], ".sqrt"))

    assign(paste0("name", vect1[i]), transform_name)
    
    for(j in 1:length(transform)){
      print(periodogram(transform[[j]], log = 'yes'))}}

source("Project/plot.roots.R")

```
# Differencing
```{r}
Mortality = Mortality.log

# To produce decomposition of Mortality:
x <- ts(as.ts(Mortality), frequency = 7)
decomp1 <- decompose(x)
plot(decomp1)

y <- ts(as.ts(Mortality), frequency = 12)
decomp2 <- decompose(y)
plot(decomp2)

z <- ts(as.ts(Mortality), frequency = 14)
decomp3 <- decompose(z)
plot(decomp3)

Frame = data.frame(matrix(nrow=8, ncol=6))
colnames(Frame) <- c("Model", "Nonseasonal", "Seasonal", "Mean", "Variance", "AICc")
Frame$Model <- c("Mortality", "Mortality_1", "Mortality_7", "Mortality_12", "Mortality_14", "Mortality_1.7", "Mortality_1.12", "Mortality_1.14")
Frame$Nonseasonal[1:8] <- c("None", 1, "None", "None", "None", 1, 1, 1)
Frame$Seasonal[1:8] <- c("None", "None", 7, 12, 14, 7, 12, 14)


# Original
plot.ts(Mortality)
nt=length(Mortality)
abline(h=mean(Mortality), col= "blue")
fit <- lm(Mortality ~ as.numeric(1:nt))
abline(fit, col="red")
x = arima(Mortality, order=c(0,0,0), method="ML")
Frame$AICc[1]=AIC(x)
Frame$Mean[1] = mean(Mortality)
Frame$Variance[1] = var(Mortality)

# Differencing Mortality:

Mortality_1 <- diff(Mortality, lag=1)
fit <- lm(Mortality_1 ~ as.numeric(1:length(Mortality_1)))
plot.ts(Mortality_1, main="(Mortality) differenced at lag 1");
abline(fit, col="red") 
abline(h=mean(Mortality_1), col="blue")
x = arima(Mortality_1, order=c(0,0,0), method="ML")
Frame$AICc[2]=AIC(x)
Frame$Mean[2] = mean(Mortality_1)
Frame$Variance[2] = var(Mortality_1)

Mortality_7 <- diff(Mortality, lag=7)
fit <- lm(Mortality_7 ~ as.numeric(1:length(Mortality_7)))
plot.ts(Mortality_7, main="(Mortality) differenced at lag 7")
abline(fit, col="red")
abline(h=mean(Mortality_7), col="blue")
x = arima(Mortality_7, order=c(0,0,0), method="ML")
Frame$AICc[3]=AIC(x)
Frame$Mean[3] = mean(Mortality_7)
Frame$Variance[3] = var(Mortality_7)

Mortality_12 <- diff(Mortality, lag=12)
fit <- lm(Mortality_12 ~ as.numeric(1:length(Mortality_12)))
plot.ts(Mortality_12, main="(Mortality) differenced at lag 12")
abline(fit, col="red")
abline(h=mean(Mortality_12), col="blue")
x = arima(Mortality_12, order=c(0,0,0), method="ML")
Frame$AICc[4]=AIC(x)
Frame$Mean[4] = mean(Mortality_12)
Frame$Variance[4] = var(Mortality_12)

Mortality_14 <- diff(Mortality, lag=14)
fit <- lm(Mortality_14 ~ as.numeric(1:length(Mortality_14)))
plot.ts(Mortality_14, main="(Mortality) differenced at lag 14")
abline(fit, col="red")
abline(h=mean(Mortality_14), col="blue")
x = arima(Mortality_14, order=c(0,0,0), method="ML")
Frame$AICc[5]=AIC(x)
Frame$Mean[5] = mean(Mortality_14)
Frame$Variance[5] = var(Mortality_14)

Mortality_1.7 <- diff(Mortality_1, lag=7)
fit <- lm(Mortality_1.7 ~ as.numeric(1:length(Mortality_1.7)))
plot.ts(Mortality_1.7, main="(Mortality) differenced at lag 1 and lag 7")
abline(fit, col="red")
abline(h=mean(Mortality_1.7), col="blue")
x = arima(Mortality_1.7, order=c(0,0,0), method="ML")
Frame$AICc[6]=AIC(x)
Frame$Mean[6] = mean(Mortality_1.7)
Frame$Variance[6] = var(Mortality_1.7)

Mortality_1.12 <- diff(Mortality_1, lag=12)
fit <- lm(Mortality_1.12 ~ as.numeric(1:length(Mortality_1.12)))
plot.ts(Mortality_1.12, main="(Mortality) differenced at lag 1 and lag 12")
abline(fit, col="red")
abline(h=mean(Mortality_1.12), col="blue")
x = arima(Mortality_1.12, order=c(0,0,0), method="ML")
Frame$AICc[7]=AIC(x)
Frame$Mean[7] = mean(Mortality_1.12)
Frame$Variance[7] = var(Mortality_1.12)

Mortality_1.14 <- diff(Mortality_1, lag=14)
fit <- lm(Mortality_1.14 ~ as.numeric(1:length(Mortality_1.14)))
plot.ts(Mortality_1.14, main="(Mortality) differenced at lag 1 and lag 14")
abline(fit, col="red")
abline(h=mean(Mortality_1.14), col="blue")
x = arima(Mortality_1.14, order=c(0,0,0), method="ML")
Frame$AICc[8]=AIC(x)
Frame$Mean[8] = mean(Mortality_1.14)
Frame$Variance[8] = var(Mortality_1.14)

Frame["Lowest AICc"] <- as.integer(rank(Frame$AICc))
Frame["Lowest Variance"] <- as.integer(rank(Frame$Variance))
Frame = Frame[1:8, c(1:5, 7, 6, 8)]
Frame

```
\
Since the trend line is the same as the mean when differencing at lag 1 and at either lag 7, lag 12, or lag 14, we will only be testing models that have a nonseasonal diference at lag 1. In addition, the largest AICcs were those with a nonseasonal and a seasonal difference.

# Differencing ACF/PACF
```{r}
x=acf2(Mortality)
x=acf2(Mortality_1)
x=acf2(Mortality_7)
x=acf2(Mortality_12)
x=acf2(Mortality_14)
x=acf2(Mortality_1.7)
x=acf2(Mortality_1.12)
x=acf2(Mortality_1.14)
```

# Test
```{r}
# Trying models. Some R Commands:

Data = data.frame(matrix(nrow=972, ncol=2))
colnames(Data) = c("Model", "AICc")

auto.arima(Mortality_1.7)

loop.s = c(7)
loop.p = c(0,1,2,3,4,5)
loop.d = c(1)
loop.q = c(0,1,2,3,4,5)
loop.P = c(0,1,2)
loop.Q = c(0,1,2)
loop.D = c(0,1,2)

i = 1
for(s in loop.s){
  for(D in loop.D){
    for(Q in loop.Q){
      for(P in loop.P){
        if(P==D & D==Q & D==0){
          for(d in loop.d){
            for(q in loop.q){
              for(p in loop.p){
                Data[i, 1] = paste0("ARIMA(", p, ",", d, ",", q, ")")
                if(p==1 & q==1){
                  assign(paste0("ARIMA(", p, ",", d, ",", q, ")"), arima(Mortality_1, order=c(p,0,q), method="ML"))
                  Data[i, 2] = AIC(get(paste0("ARIMA(", p, ",", d, ",", q, ")")))
                  x=acf2(get(paste0("ARIMA(", p, ",", d, ",", q, ")"))$residuals, main = paste0("ARIMA(", p, ",", d, ",", q, ")  AICc = ", Data[i,2]))}
                else{
                  assign(paste0("ARIMA(", p, ",", d, ",", q, ")"), arima(Mortality, order=c(p,d,q), method="ML"))
                  Data[i, 2] = AIC(get(paste0("ARIMA(", p, ",", d, ",", q, ")")))
                  x=acf2(get(paste0("ARIMA(", p, ",", d, ",", q, ")"))$residuals, main = paste0("ARIMA(", p, ",", d, ",", q, ")  AICc = ", Data[i,2]))}}
              i=i+1}}}
        else{
          for(d in loop.d){
            for(q in loop.q){
              for(p in loop.p){
                if(p==d & q==d){
                  Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)
                  assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), arima(Mortality_1, order=c(p,0,q), seasonal=list(order=c(P,D,Q), period=s), method="ML"))
                  Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                  x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))}
                else{
                  Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)
                  assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), arima(Mortality, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s), method="ML"))
                  Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                  x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))}
              i = i + 1}}}}}}}}

Data["Lowest AICc"] <- as.integer(rank(Data$AICc))
Data
arima(Mortality, order = c(1,1,1), seasonal=list(order=c(1,1,1), period = 7))
auto.arima
```



```{r}
Data = data.frame(matrix(nrow=972, ncol=2))
colnames(Data) = c("Model", "AICc")

loop.s = c(7)
loop.p = c(0,1,2,3,4,5)
loop.d = c(1)
loop.q = c(0,1,2,3,4,5)
loop.P = c(0,1,2)
loop.Q = c(0,1,2)
loop.D = c(0,1,2)

i = 1
for(s in loop.s){
  for(D in loop.D){
    for(Q in loop.Q){
      for(P in loop.P){
        for(d in loop.d){
          for(q in loop.q){
            for(p in loop.p){
              if((p==3 & d==1 & q==2 & P==1 & Q==1 & D==0) | (p==5 & d==1 & q==5 & P==1 & Q==1 & D==0) | (p==3 & d==1 & q==2 & P==2 & Q==1 & D==0) | (p==1 & d==1 & q==3 & P==2 & Q==1 & D==0) | (p==4 & d==1 & q==4 & P==2 & Q==1 & D==0)){
                Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s)))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))}
              else{
                if(P==0 & Q==0 & D==0){
                  Data[i, 1] = paste0("ARIMA(", p, ",", d, ",", q, ")")}
                else{
                  Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)}
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s), method="ML"))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))
              i=i+1}}}}}}}}
                  
auto.arima(Mortality)
```


```{r}
Data = data.frame(matrix(nrow=972, ncol=2))
colnames(Data) = c("Model", "AICc")

loop.s = c(7)
loop.p = c(0,1,2,3,4,5)
loop.d = c(1)
loop.q = c(0,1,2,3,4,5)
loop.P = c(0,1,2)
loop.Q = c(0,1,2)
loop.D = c(0,1,2)

i = 1
for(s in loop.s){
  for(D in loop.D){
    for(Q in loop.Q){
      for(P in loop.P){
        for(d in loop.d){
          for(q in loop.q){
            for(p in loop.p){
              if((p==3 & d==1 & q==2 & P==1 & Q==1 & D==0) | (p==5 & d==1 & q==5 & P==1 & Q==1 & D==0) | (p==3 & d==1 & q==2 & P==2 & Q==1 & D==0) | (p==1 & d==1 & q==3 & P==2 & Q==1 & D==0) | (p==4 & d==1 & q==4 & P==2 & Q==1 & D==0)){
                Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality1, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s)))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))}
              else{
                if(P==0 & Q==0 & D==0){
                  Data[i, 1] = paste0("ARIMA(", p, ",", d, ",", q, ")")}
                else{
                  Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)}
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s), method="ML"))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))
              i=i+1}}}}}}}}

```
```{r}
source('plot.roots.R')

read_file('plot.roots.R')
plot.roots(`SARIMA(5,1,5)x(1,0,1)_7`)
`SARIMA(5,1,5)x(1,0,1)_7`
`SARIMA(5,1,5)x(1,0,1)_7(fixed)` = arima(Mortality, order = c(5,1,5), seasonal=list(order=c(1,0,1), period=7), method="ML", fixed = c(0,0,0,0,0,0,0,0,0,0,0,NA))
acf2(`SARIMA(5,1,5)x(1,0,1)_7(fixed)`$residuals)    

`SARIMA(5,1,4)x(0,0,1)_7(fixed)` = arima(Mortality, order=c(5,1,4), seasonal=list(order=c(0,0,1), period=7), method="ML", fixed= c(0, NA, NA, NA, NA, NA, NA, NA, NA, NA))

acf(`SARIMA(5,1,4)x(0,0,1)_7(fixed)`$residuals)
mtext("hello",  side=1, srt=-90, line=2, h.just=2)
`SARIMA(5,1,5)x(0,0,2)_7`

`SARIMA(5,1,5)x(0,0,2)_7(fixed)` = arima(Mortality, order=c(5,1,5), seasonal=list(order=c(0,0,2), period=7), method="ML", fixed= c(0, NA, NA, NA, NA, NA, NA, 0, NA, NA, NA, NA))
acf2(`SARIMA(5,1,5)x(0,0,2)_7(fixed)`$residuals)
x=Box.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals, lag=40, type=c("Box-Pierce"), fitdf = 11)
x$p.value
`SARIMA(3,1,2)x(1,0,1)_7`
kpss.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals)
check.statio
acf2(`SARIMA(3,1,2)x(2,0,1)_7`$residuals)

`SARIMA(3,1,2)x(1,0,1)_7(fixed)` = arima(Mortality, order=c(3,1,2), seasonal=list(order=c(1,0,1), period=7), method="ML", fixed= c(NA, 0, NA, NA, NA, 0, NA))
acf2(`SARIMA(3,1,2)x(1,0,1)_7(fixed)`$residuals)
adf
kpss.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals)
autoplot(`SARIMA(4,1,4)x(2,0,1)_7`$residuals)
plot(`SARIMA(4,1,4)x(2,0,1)_7`$root)

`SARIMA(3,1,2)x(1,0,1)_7(fixed)` = arima(Mortality, order=c(3,1,2), seasonal=list(order=c(1,0,1), period=7), method="ML", fixed= c(NA, 0, NA, NA, NA, 0, NA))
acf2(`SARIMA(3,1,2)x(1,0,1)_7(fixed)`$residuals)

acf2(arima(Mortality, order = c(5,1,5), seasonal=list(order=c(1,0,1), period=7), method="ML")$residuals)



acf2(`SARIMA(4,1,4)x(2,0,1)_7`$residuals)
mtext(paste0("Box-Pierce: p-value = ", signif(Box.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals, lag=sqrt(1228), type=c("Box-Pierce"), fitdf = 11)$p.value, digits=3), "________________________________Ljung-Box: p-value = ", signif(Box.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals, lag=sqrt(1228), type=c("Ljung-Box"), fitdf = 11)$p.value, digits=3)),  side=1, line=-6, adj=0, cex=.8)
mtext(paste0("McLeod-Li: p-value = ", signif(Box.test((`SARIMA(4,1,4)x(2,0,1)_7`$residuals)^2, lag=sqrt(1228), type=c("Ljung-Box"), fitdf = 11)$p.value, digits=3), "_________________________________Shapiro: p-value = ", signif(shapiro.test(`SARIMA(4,1,4)x(2,0,1)_7`$residuals)$p.value, digits=3)),  side=1, line=-7, adj=0, cex=.8)


```


```{r}
Data = data.frame(matrix(nrow=972, ncol=2))
colnames(Data) = c("Model", "AICc")

loop.s = c(7)
loop.p = c(0,1,2,3,4,5)
loop.d = c(1)
loop.q = c(0,1,2,3,4,5)
loop.P = c(0,1,2)
loop.Q = c(0,1,2)
loop.D = c(0,1,2)

i = 1
for(s in loop.s){
  for(D in loop.D){
    for(Q in loop.Q){
      for(P in loop.P){
        for(d in loop.d){
          for(q in loop.q){
            for(p in loop.p){
              if((p==3 & d==1 & q==2 & P==1 & Q==1 & D==0) | (p==5 & d==1 & q==5 & P==1 & Q==1 & D==0) | (p==3 & d==1 & q==2 & P==2 & Q==1 & D==0) | (p==1 & d==1 & q==3 & P==2 & Q==1 & D==0) | (p==4 & d==1 & q==4 & P==2 & Q==1 & D==0)){
                Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality2, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s)))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))}
              else{
                if(P==0 & Q==0 & D==0){
                  Data[i, 1] = paste0("ARIMA(", p, ",", d, ",", q, ")")}
                else{
                  Data[i, 1] = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)}
                assign(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s), 
                       arima(Mortality, order=c(p,d,q), seasonal=list(order=c(P,D,Q), period=s), method="ML"))
                Data[i, 2] = AIC(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s)))
                x=acf2(get(paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s))$residuals, 
                       main = paste0("SARIMA(", p, ",", d, ",", q, ")x(", P, ",", D, ",", Q, ")_", s, "  AICc = ", Data[i,2]))
              i=i+1}}}}}}}}
                  

```



```{r}     
          acf2(assign(paste0("SARIMA(", p, "_1_", q, ")x(0,1,0)_", s), arima(Mortality_1, order=c(p,0,q), seasonal=list(order=c(0,1,0), period=s), method="ML"))$residuals, main = paste0("SARIMA(", p, "_1_", q, ")x(0,1,0)_", s))}
        else{
          acf2(assign(paste0("SARIMA(", p, "_1_", q, ")x(0,1,0)_", s), arima(Mortality, order=c(p,1,q), seasonal=list(order=c(0,1,0), period=s), method="ML"))$residuals, main = paste0("SARIMA(", p, "_1_", q, ")x(0,1,0)_", s))}}}}}
x=arima(Mortality)
plot(x)
      
    assign(paste0("ARIMA1_", p, "_1_", q), arima(Mortality_1, order=c(p,1,q), seasonal=list(order=c(0,1,0), period=12), method="ML"))
    acf2(assign(paste0("Residuals_ARIMA_0_1_", i,  "_of_", x), arima(Mortality, order=c(0,1,i), method="ML")$residuals), main = paste0("ARIMA_0_1_", i, " of ", x))
    variable1 = paste0("ARIMA_0_1_", i)
    variable2 = paste0("Residuals_ARIMA0_1_", i,  "_of_", x)
}}

```

```{r}

  arima(Mortality, order=c(1,1,1), seasonal = list(order = c(0,1,1), period = 0), method="ML")
  acf2(x
# Model
Model1 = arima(Mortality.stat, order=c(0,1,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")

Model1

x = acf2(Model1)

AICc(Model1)



x=residuals(covid["new_cases_smoothed"])


x

arima(Mortality, order=c(4,1,5), seasonal = list(order = c(1,0,1), period = 7), method = "ML")

AICc(arima(Mortality, order=c(0,1,3), seasonal = list(order = c(0,1,1), period = 12), method="ML"));
[1] -441.0091
arima(Mortality, order=c(0,1,3), seasonal = list(order = c(0,1,1), period = 12), fixed = c(NA, 0, NA, NA),
method="ML")
ma1 ma2 ma3 sma1 -0.3353 0 -0.1612 -0.5782
s.e. 0.0810 0 0.0852 0.0796
sigma^2 estimated as 0.00127: log likelihood = 225.38, aic = -442.76
AICc(arima(Mortality, order=c(0,1,3), seasonal = list(order = c(0,1,1), period = 12), fixed = c(NA, 0, NA, NA), method="ML")) [1] -442.4489
32
polyroot(c(1, 0.87, 0.76))
  • To check invertibility of MA part of model A:
source("plot.roots.R")
plot.roots(NULL,polyroot(c(1, -0.3353, 0, -0.1612)), main="(A) roots of ma part, nonseasonal ")
• Diagnostic checking of model B:
fit <- arima(Mortality, order=c(0,1,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")
res <- residuals(fit)
hist(res,density=20,breaks=20, col="blue", xlab="", prob=TRUE)
m <- mean(res)
std <- sqrt(var(res))
curve( dnorm(x,m,std), add=TRUE )
plot.ts(res)
fitt <- lm(res ~ as.numeric(1:length(res))); abline(fitt, col="red")
abline(h=mean(res), col="blue")
qqnorm(res,main= "Normal Q-Q Plot for Model B")
qqline(res,col="blue"
acf(res, lag.max=40)
pacf(res, lag.max=40)
shapiro.test(res)
Box.test(res, lag = 12, type = c("Box-Pierce"), fitdf = 2) Box.test(res, lag = 12, type = c("Ljung-Box"), fitdf = 2)
Box.test(res^2, lag = 12, type = c("Ljung-Box"), fitdf = 0)
acf(res^2, lag.max=40)
ar(res, aic = TRUE, order.max = NULL, method = c("yule-walker"))

• Forecasting using model A:
install.packages("forecast")
library(forecast)
fit.A <- arima(Mortality, order=c(0,1,3), seasonal = list(order = c(0,1,1), period = 12),
fixed = c(NA, 0, NA, NA), method="ML")
forecast(fit.A) % prints forecasts with prediction bounds in a table
• To produce graph with 12 forecasts on transformed data:
pred.tr <- predict(fit.A, n.ahead = 12)
U.tr= pred.tr$pred + 2*pred.tr$se % upper bound of prediction interval L.tr= pred.tr$pred - 2*pred.tr$se % lower bound
ts.plot(Mortality, xlim=c(1,length(Mortality)+12), ylim = c(min(Mortality),max(U.tr)))
lines(U.tr, col="blue", lty="dashed")
lines(L.tr, col="blue", lty="dashed")
points((length(Mortality)+1):(length(Mortality)+12), pred.tr$pred, col="red")
34

  • To produce graph with forecasts on original data:
pred.orig <- exp(pred.tr$pred)
U= exp(U.tr)
L= exp(L.tr)
ts.plot(Mortality, xlim=c(1,length(Mortality)+12), ylim = c(min(Mortality),max(U))) lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points((length(Mortality)+1):(length(Mortality)+12), pred.orig, col="red")
• To zoom the graph, starting from entry 100:
ts.plot(Mortality, xlim = c(100,length(Mortality)+12), ylim = c(250,max(U))) lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points((length(Mortality)+1):(length(Mortality)+12), pred.orig, col="red")
• To plot zoomed forecasts and true values (in Mortality):
ts.plot(Mortality, xlim = c(100,length(Mortality)+12), ylim = c(250,max(U)), col="red") lines(U, col="blue", lty="dashed")
lines(L, col="blue", lty="dashed")
points((length(Mortality)+1):(length(Mortality)+12), pred.orig, col="green")
points((length(Mortality)+1):(length(Mortality)+12), pred.orig, col="black")


```

```{r}



```

```{r}



```

```{r}



```


```{r}
Mortality.diff7 = diff(Mortality, lag=7, differences=2)
Mortality.diff8 = diff(Mortality.diff7, 1)
plot.ts(Mortality.diff)
Mortality.diff_acf1
acf2(Mortality.diff7)

acf2(Mortality.diff8)
var(Mortality.diff)

Mortality.diff2 = diff(Mortality, 2)
plot.ts(Mortality.diff2)
Mortality_acf2 = acf2(Mortality.diff2)
var(Mortality.diff2)

Mortality.diff3 = diff(Mortality, 3)
plot.ts(Mortality.diff3)
Mortality_acf3 = acf2(Mortality.diff3)
var(Mortality.diff3)

Mortality.diff4 = diff(Mortality, 4)
plot.ts(Mortality.diff4)
Mortality_acf4 = acf2(Mortality.diff4)
var(Mortality.diff4)
adf.test
# Diff = 1
var(Mortality.diff) < var(Mortality.diff2)

ar1 = ar(Mortality.diff, aic = FALSE, method="mle") # 12
ar2 = ar(Mortality.diff, aic = FALSE, method="yw") # 29
ar3 = ar(Mortality.diff, aic = TRUE, method="mle") # 10
ar4 = ar(Mortality.diff, aic = TRUE, order.max = 12, method="yw") # 10

source("innovations.R")

acvf = acf(Mortality.diff, plot=FALSE, lag.max = length(Mortality.diff))$acf[,1,1] * var(Mortality.diff) 
m = length(acvf)
lh.ia = innovations.algorithm(m+1, acvf)
lh.ia$thetas[9,1:9] # Preliminary estimates of coefficients for MA(9)
lh.ia$thetas[10,1:10] # Preliminary estimates of coefficients for MA(10)
lh.ia$thetas[11,1:11] # Preliminary estimates of coefficients for MA(11)
lh.ia$thetas[12,1:12] # Preliminary estimates of coefficients for MA(12)

arima1 <- auto.arima(Mortality, start.p = 0, start.q = 0, d=1, start.P = 0, start.Q = 0, stationary=TRUE, seasonal = TRUE, allowmean=TRUE, trace = TRUE) # 5,0,0

fit.ar1 <- arima(Mortality.diff8, order=c(1,1,7), seasonal=list(order=c(6,2,2), period=7))

fit.ar1.1 <- arima(Mortality.diff8, order=c(1,1,7), seasonal=list(order=c(4,2,2), period=7), fixed=c(NA,NA,NA,0,0,NA,NA,NA,NA,NA,NA,NA,NA,NA))

a=acf2(fit.ar1.1$residuals)
acf2(fit.ar1$residuals)
a
fit.ar1
fit.ar2 <- arima(Mortality.diff8, order=c(7,1,7), seasonal=list(order=c(6,2,1), period=7))
acf2(fit.ar2$residuals)

fit.ar2 <- arima(Mortality.diff, order=c(0,0,0))

acf1 = acf2(fit.ar1$residuals)
acf1

fit.ar2 <- arima(Mortality, order=c(8,1,1))
fit.ar2 
acf2 = acf2(fit.ar2$residuals)
acf1 = acf2(fit.ar1$residuals)

fit.sarima = astsa::sarima(Mortality,8,1,1,0,1,0,7, model=TRUE)
acf2(fit.sarima$fit$residuals)

fit.ar3.1
fit.ar3.2

fit.ar3.1 <- arima(Mortality, transform.pars = TRUE, method="ML", order=c(0,1,10), seasonal=list(order=c(0,1,1), period=14), include.mean=TRUE, fixed=c(NA,NA,NA,NA,NA,NA,NA,NA,0,NA,NA))

fit.ar3.2 <- arima(Mortality, transform.pars = TRUE, method="ML", order=c(0,1,10), seasonal=list(order=c(0,1,1), period=14), include.mean=TRUE)
acf2(fit.ar3.1$residuals)

acf2(fit.ar3.2$residuals)
                 
fit.ar3 <- arima(Mortality, order=c(0,1,15), seasonal=list(order=c(0,1,1), period=14), fixed=c(NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0,0,0,0,0,NA), a)

fit.ar4 <- arima(Mortality, order=c(0,1,7), seasonal=list(order=c(0,1,1), period=14))

fit.ar5 <- arima(Mortality, order=c(5,1,10), seasonal=list(order=c(0,1,1), period=14))
fit.ar5
acf5


fit.ar5.1 <- arima(Mortality, order=c(5,1,), seasonal=list(order=c(0,1,1), period=14), fixed = c(0,NA,0,0,NA,0,0,0,0,0,0,NA,NA))

fit.ar5.1
fit.ar5
plot(fit.ar5)
acf3 = acf2(fit.ar3$residuals)
acf3.1 = acf2(fit.ar3.1$residuals)
acf4 = acf2(fit.ar4$residuals)
acf5.1 = acf2(fit.ar5.1$residuals)
acf5 = acf2(fit.ar5$residuals, plot=FALSE)
acf5
fit.ar5
Mortality.diff_acf1 = acf2(Mortality.diff)


fit.ar2 <- arima(Mortality.diff, order=c(10,0,0))
fit.ar3 <- arima(Mortality.diff, order=c(12,0,0))
fit.ar4 <- arima(Mortality.diff, order=c(29,0,0))

fit.ma5 <- arima(Mortality.diff, order=c(0,0,9))
fit.ma6 <- arima(Mortality.diff, order=c(0,0,10))
fit.ma7 <- arima(Mortality.diff, order=c(0,0,11))
fit.ma8 <- arima(Mortality.diff, order=c(0,0,12))

fit.arma9 <- arima(Mortality.diff, order=c(5,0,9)) # 12/14 0.05 < s.e. < 0.21
fit.arma10 <- arima(Mortality.diff, order=c(5,0,10)) # NAN produced
fit.arma11 <- arima(Mortality.diff, order=c(5,0,11)) # all 0.07 < s.e. < 0.77
fit.arma12 <- arima(Mortality.diff, order=c(5,0,12)) # 13/17 0.05 < s.e. < 0.837

fit.arma13 <- arima(Mortality.diff, order=c(10,0,9)) # NAN produced
fit.arma14 <- arima(Mortality.diff, order=c(10,0,10)) # 18/20  0.05 < s.e. < 0.099
fit.arma15 <- arima(Mortality.diff, order=c(10,0,11)) # all 0.97 < s.e. < 0.32
fit.arma16 <- arima(Mortality.diff, order=c(10,0,12)) # all 0.12 < s.e. < 0.61

fit.arma17 <- arima(Mortality.diff, order=c(12,0,9)) # all 0.05 < s.e. < 0.60
fit.arma18 <- arima(Mortality.diff, order=c(12,0,10)) # NAN produced
fit.arma19 <- arima(Mortality.diff, order=c(12,0,11)) # NAN produced
#fit.arma20 <- arima(Mortality.diff, order=c(12,0,12)) # all 0.09 < s.e. < 0.37
#fit.arma21 <- arima(Mortality.diff, order=c(29,0,9)) # NAN produced
#fit.arma22 <- arima(Mortality.diff, order=c(29,0,10)) # NAN produced
# fit.arma23 <- arima(Mortality.diff, order=c(29,0,11)) # NAN produced
# fit.arma24 <- arima(Mortality.diff, order=c(29,0,12)) # NAN produced

# STATIONARY
fit.arma25_10 <- arima(Mortality.diff, order=c(25,0,10)) # NAN produced
# STATIONARY w/out NANs for s.e. 
fit.arma25_9 <- arima(Mortality.diff, order=c(25,0,9)) # NAN produced

Data <- data.frame(c(AICc(fit.ar1),
AICc(fit.ar2),
AICc(fit.ar3),
AICc(fit.ar4),
AICc(fit.ma5),
AICc(fit.ma6),
AICc(fit.ma7),
AICc(fit.ma8),
AICc(fit.arma9),
AICc(fit.arma10),
AICc(fit.arma11),
AICc(fit.arma12),
AICc(fit.arma13),
AICc(fit.arma14),
AICc(fit.arma15),
AICc(fit.arma16),
AICc(fit.arma17),
AICc(fit.arma18),
AICc(fit.arma19),
#AICc(fit.arma20),
#AICc(fit.arma21),
#AICc(fit.arma22),
AICc(fit.arma25_10),
AICc(fit.arma25_9)))

rownames(Data) <- c("AR(5)", "AR(10)", "AR(12)", "AR(29)", "MA(9)", "MA(10)", "MA(11)", "MA(12)", "ARMA(5,9)", "ARMA(5,10)", "ARMA(5,11)", "ARMA(5,12)", "ARMA(10,9)", "ARMA(10,10)", "ARMA(10,11)", "ARMA(10,12)", "ARMA(12,9)", "ARMA(12,10)", "ARMA(12,11)", "ARMA(25,10)", "ARMA(25,9)")
colnames(Data) <- c("AICc")

Data["Lowest AICc"] <- as.integer(rank(Data$AICc))
Data

acf1 = acf2(fit.ar1$residuals)
acf2 = acf2(fit.ar2$residuals)
acf3 = acf2(fit.ar3$residuals)
acf4 = acf2(fit.ar4$residuals)
acf5 = acf2(fit.ma5$residuals)
acf6 = acf2(fit.ma6$residuals)
acf7 = acf2(fit.ma7$residuals)
acf8 = acf2(fit.ma8$residuals)
acf9 = acf2(fit.arma9$residuals)
acf10 = acf2(fit.arma10$residuals)
acf11 = acf2(fit.arma11$residuals)
acf12 = acf2(fit.arma12$residuals)
acf13 = acf2(fit.arma13$residuals)
acf14 = acf2(fit.arma14$residuals)
acf15 = acf2(fit.arma15$residuals)
acf16 = acf2(fit.arma16$residuals)
acf17 = acf2(fit.arma17$residuals)
acf18 = acf2(fit.arma18$residuals)
acf19 = acf2(fit.arma19$residuals)
#acf20 = acf2(fit.arma20$residuals)
#acf21 = acf2(fit.arma21$residuals)
#acf22 = acf2(fit.arma22$residuals)
acf23 = acf2(fit.arma25_10$residuals)
acf24 = acf2(fit.arma25_9$residuals)

```
