---
title: "PSTAT 174/274 Spring 2023 Homework 6"
author: "Dylan Berneman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1
The three models AR(2), MA(1), and ARMA(2,1) are fitted to the following time series:


| Year | Quarter 1 | Quarter 2 | Quarter 3 | Quarter 4 |
|:-------:|:------:|:-----------:|:---------:|:--------:| 
| 2010 | 112 | 104 | 100 | 96 |
| 2011 | 101 | 101 | 105 | 94 |
| 2012 | 106 | 106 | 108 | 110 |
\


**AR(2)**\

|  | ar1 | ar2 | intercept | 
|:-------:|:------:|:-----------:|:---------:|
|  | 0.2618 | 0.0868 | 104.227 |
| st. error | 0.3289 | 0.3326 | 2.372 |
| $\sigma^2$ = 25.02 |  | log likelihood = -36.4 |  |
\

**MA(1)**\

|  | ma1 | intercept | 
|:-------:|:------:|:-----------:|
|  | 0.1899 | 103.798 |
| st. error | 0.2574 | 1.7373 |
| $\sigma^2$ = 25.66 |  | log likelihood = -36.51 |

\

**ARMA(2,1)**\

|  | ar1 | ar2 | ma1 | intercept | 
|:-------:|:------:|:-----------:|:---------:|:-----:|
|  | -0.5547 | 0.4437 | 0.9779 | 104.4542 |
| st. error | 0.3329 | 0.33267 | 0.235 | 2.4584 |
| $\sigma^2$ = 21.31 |  | log likelihood = -36.02 |  |
\

The models are ranked using Akaike Information Criterion, Corrected for bias (AICC) (see §11.3 of Lecture Notes or slide 32 of week 5).\
AICC = −2× log-likelihood+2 × $\frac{rn}{n-r-1}$ where n is the sample size and r is the number of free parameters, n−r−1
most often r = p + q + 1.\
Determine the order from the best to worst model. Give full explanation on how you arrived to your answer. Show calculations.\

  (A) AR(2), MA(1), ARMA (2,1) 
  (B) AR(2), ARMA (2,1), MA(1) 
  (C) MA(1), AR(2), ARMA (2,1) 
  (D) MA(1), ARMA (2,1), AR(2) 
  (E) ARMA (2,1), AR(2), MA(1)\
  
$$
\begin{aligned}
\text{AICC}:&\\\\
\text{AR(2)}:& \ \ p=2,\ q=0,\ r=3,\ n=12\  \\
&=-2 * -36.4 + 2 * \frac{3*12}{12-3-1}\\
&=72.8 + 9\\
&=81.8\\\\
\text{MA(1)}:& \ \ p=0,\ q=1,\ r=2,\ n=12\  \\
&=-2 * -36.51 + 2 * \frac{2*12}{12-2-1}\\
&=73.02 + 48/9\\
&=78.353\\\\
\text{ARMA(2,1)}:& \ \ p=2,\ q=1,\ r=4,\ n=12\  \\
&=-2 * -36.02 + 2 * \frac{4*12}{12-4-1}\\
&=72.04 + 96/7\\
&=85.754\\\\
\text{Order:}&\ \text{ARMA(2,1), AR(2), MA(1)}\\\\
Answer:\ E.
\end{aligned}
$$
\
\

### Question 3
In modeling the weekly sales of a certain commodity over the past six months, the time series model X~t~ − $\phi$~1~X~t−1~ = Z~t~ + θ~1~Z~t−1~ was thought to be appropriate. Suppose the model was fitted and the autocorrelations of the residuals were:\

| k | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| $\hat{\rho}_{\hat{W}}(k)$ | -.04 | -.50 | .03 | -.01 | .01 | .02 | .03 | -.01 |
| st. dev $\hat{\rho}_{\hat{W}}(k)$ | .08 | .10 | .11 | .11 | .11 | .11 | .11 | .11 |
\
Is the assumed model really appropriate? If not, how would you modify the model? Explain.\

*Hint: Check slides 8 - 9 of Lecture 11 for the 95% confidence intervals for autocorrelation function of the fitted residuals. You might also find slide 26 of Week 2 and slide 15 of Lecture 11 useful.*\

$$
\begin{aligned}
& \text{For each lag, check if the coefficient is significant}\\\\
&\text{Significant if } |\frac{acf[x]}{std. dev[x]}| \ge 1.96\\\\
&\text{lag 1 }: |\frac{-0.04}{0.08}| = 0.5 \ngeq 1.96\\
&\text{lag 2 }: |\frac{-0.50}{0.10}| = 5 \geq 1.96\\
&\text{lag 3 }: |\frac{0.03}{0.11}| = 0.2727 \ngeq 1.96\\
&\text{lag 4 }: |\frac{-0.01}{0.11}| = 0.0909 \ngeq 1.96\\
&\text{lag 5 }: |\frac{-0.04}{0.08}| = 0.0909 \ngeq 1.96\\
&\text{lag 6 }: |\frac{0.01}{0.11}| = 0.1818 \ngeq 1.96\\
&\text{lag 7 }: |\frac{0.02}{0.11}| = 0.2727 \ngeq 1.96\\
&\text{lag 8 }: |\frac{0.03}{0.11}| = 0.0909 \ngeq 1.96\\\\
&\text{Since the first and only significant acf value occurs at lag 2,}\\
&\text{then that means that the coefficients values of}\ \phi_1 \&\ \theta_1 = 0.\\
&\text{This implies that the next significant lag value should be the}\\
&\text{minimum order of the ARMA model. Since all other acf values}\\
&\text{can be considered to be 0, this should actually be an MA(2) model}\\
&\text{of the form: } X_t = Z_t - \theta_1Z_{t-2}.\\
&\text{Therefore, the assumed model is not appropriate.}
\end{aligned}
$$
\
\

### Question 3 
Suppose that in a sample of size 100 from an AR(1) process with mean μ, $\phi$ = 0.6, and σ^2^ = 2, we obtain $\bar{x}_{100}$ = 0.271. Construct an approximate 95% confidence interval for μ. Are the data compatible with the hypothesis that μ = 0?\



*Help: (i) Here σ^2^ ≡ σ~Z~^2^ is the variance of noise Zt.*\
*(ii) Large sample distribution of $\bar{X}_n$ is given as follows (See, for example, slide 48 or §10.1 of Week 4): For n large, distribution of the sample mean $\bar{X}_n$ is approximately normal with mean μ ≡ EXt and variance n^−1^v, where v ≈ γ~X~(0) + 2 $\sum_{h=1}^{\infty}$ γ~X~(h).*\
*(iii) For ACVF for AR(1) process see slide 43 of Week 2.*


$$
\begin{aligned}
&\text{Given: } n=100,\\
& \ \ \ \ \ \ \ \ \ \ \ \phi_1=0.6,\\
& \ \ \ \ \ \ \ \ \ \ \ \sigma^2=2,\\
& \ \ \ \ \ \ \ \bar{X}_{100}=0.271\\\\
&\text{For stationary time series X:}&\\
&\bullet\ \text{Sample Mean: }\bar{X}_n \\
&\bullet\ \text{Confidence Interval: For n large, distribution of the sample mean }\bar{X}_n\\
&\ \ \ \ \  \text{is approximately normal with mean µ = }E[X_t]\ \text{and variance } n^{-1}v\\\\
&\text{Confidence Interval for } \mu:\ 
(\bar{X}_n\ \pm\ 1.96\ v^{1/2}/\sqrt{n})\\
& v = \gamma_X(0)+2\sum_{1\leq\ h}^{n}\gamma_X(h)\\\\
& \gamma_X(0) = \frac{\sigma_X^2}{1-\phi_1^2}\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \gamma_X(h)= \phi_1^h\gamma_X(0);\ \\
&\ \ \ \ \ \ \ \ \ \ = \frac{2}{1-0.6^2}\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  = 0.6^h*3.125\\
&\ \ \ \ \ \ \ \ \ \ = 3.125 \\
&v=3.125 + 2\sum_{h=1}^{n=100}0.6^h*3.125\\
& \ \  = 3.125 + 6.25\sum_{1}^{100}0.6^h\\
& \ \ = 3.125 + 6.25(0.6*\frac{1-0.6^{100}}{1-0.6})\\
& \ \ = 3.125 + 4(1.5)\\
& \ \ = 12.5\\
&v^{1/2} = 3.536\\\\
&\text{CI}:\ (0.271\ \pm\ 1.96(3.536)/10)\\
& \ \ \ \ \ \ \ \ \  (0.271\ \pm\ 0.693)\\ 
& \ \ \ \ \ \ \ \ \  (-0.422,\ 0.964)\\\\
&\text{The data is compatible with the hypothesis that µ=0}
\end{aligned}
$$
\
\

**The following problem is for students enrolled in PSTAT 274 ONLY**
\

### Question G1
Two hundred observations of a time series, X~1~, . . . , X~200~, gave the following sample statistics: sample mean: $\bar{X}_200$ = 3.82; sample variance: $\hat{γ}(0)$ = 1.15; sample ACF: $\hat{ρ}(1)$ = .427, $\hat{ρ}(2)$ = .475, $\hat{ρ}(3)$ = .169.\

  (a) Based on these sample statistics, is it reasonable to suppose that {X~t~ − μ} is a white noise?\

$$
\begin{aligned}
&\text{For white noise, sample ACFs should be within the interval: }\\
&\ \ \ \ \pm 1.96/n^{1/2}\\
& = \pm 1.96/200^{1/2}\\
&= \pm 1.96/14.14\\
&= \pm 0.1386\\
& (-0.1386,\ 0.1386)\\\\
&\text{Since none of the three sample ACFs are within this interval,}\\
&\text{it is not reasonable to assume that }X_t-\mu\ \text{is a white noise.}
\end{aligned}
$$
\
\

  (b) Assuming that {Xt − μ} can be modeled as the AR(2) process,
X~t~ −μ−$\phi_1$(X~t−1~ −μ)−$\phi_2$(X~t−2~ −μ)=Z~t~,
where Z~t~ ∼ IID(0, σ~Z~^2^ ), find estimates of μ, $\phi_1$, $\phi_2$, and σ~Z~^2^ .\

$$
\begin{aligned}
&\text{If the series can be modeled as the AR(2) process,}\\
&\text{then the ACF at lags 1 and 2 should be }\hat{ρ}(1) = 0.427\ \&\ \hat{ρ}(2) = 0.475.\\
& \rho_X(1) = \phi_1+\phi_2\rho_X(1)\\
&0.427 = \phi_1+\phi_2(0.427)\\
& \phi_1=0.427(1-\phi_2)\\\\
& \rho_X(2) = \phi_1\rho_X(1)+\phi_2\\
&0.475 = \phi_1(0.427)+\phi_2\\
&0.475 = 0.427(1-\phi_2)(0.427)+\phi_2\\
&0.475 = 0.182329-0.182329\phi_2+\phi_2\\
&0.292671=0.817671\phi_2\\
&\phi_2 = 0.292671/0.817671\\
& \ \ \ \ = 0.3579\\\\
& \phi_1=0.427(1-\phi_2)\\
& \ \ \ \ =0.427(1-0.3579)\\
& \ \ \ \ =0.427(0.64207)\\
& \ \ \ \ =0.2742\\\\
& \mu = 3.82,\ \ \ \ \ \ \phi_1 = 0.2742,\ \ \ \ \ \ \phi_2=0.3579
\end{aligned}
$$
\

  (c) Assuming that the data was generated from an AR(2) model, derive estimates of the PACF for all lags h ≥ 1.\
  
$$
\begin{aligned}
\text{PACF of AR(2) } &=
\begin{cases}
\phi_1/(1-\phi_2)\ \ \ \ \ for\ h=1\\
\phi_2 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ for\ h=2\\
0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ for\ h \ge 3
\end{cases}\\\\
& = \begin{cases}
0.2742/(1-0.3579)\ \ \ \ \ for\ h=1\\
0.3579\ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ for\ h=2\\
0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ for\ h \ge 3
\end{cases}\\\\
& = \begin{cases}
0.427\ \ \ \ \ \ \ \  \ \ for\ h=1\\
0.3579\ \ \ \ \ \ \ \ for\ h=2\\
0 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ for\ h \ge 3
\end{cases}\\
\end{aligned}
$$