---
title: "PSTAT 174/274, Spring 2023: Homework #3"
author: "Dylan Berneman"
date: '2023-04-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

. Note: {Zt} ∼ WN(0,σZ2 ) denotes white noise.
1. You are given the following time series model: Xt = 23 Xt−1 + 12 Xt−2 + Zt. Determine whether this time series is stationary and/or invertible.
2. You are given the following statements about a time series modeled as an AR(3) process: I. Partial Autocorrelation for lag 3 is always equal to zero.
II. Partial Autocorrelation for lag 4 is always equal to zero.
III. Partial Autocorrelation for lag 4 is always greater than zero.
Determine which of the above statements are true.
3. For a stationary ARMA(1,1) model, you are given the following information: ρX(1) = 0.7, ρX(2) = 0.3. Calculate φ1.
Hint: Formulas for ACF of ARMA (1,1) model Xt − φ1Xt−1 = Zt + θ1Zt−1 are given in §5.1 of lecture notes and slide 24 of week 3. Can you determine a recursive relation between ρX (k) and ρX (k − 1)? Use it!
4. You are given PACF for a stationary process: φ11 = −0.60, φ22 = 0.36, φkk = 0 for k ≥ 3. What time series model could have this PACF? Identify model’s coefficients and write model equation.
Hint: • §6 of Lecture Notes and slides 32-33 of Week 3 provide relationship between PACF and ACF, allowing to calculate ACFs of the model from given PACFs.
• Yule-Walker equations, in §4.3 of Lecture Notes and on slide 14, Week 3, provide relationship between ACF and model coefficients.
5. You are given the following time-series model: Xt = 0.8Xt−1 + 2 + Zt − 0.5Zt−1. Which of the following statements about this model is false?
A. ρX(1) = 0.4. B. ρX(k) < ρX(1),k ≥ 2. C. The model is ARMA(1,1). D. The model is stationary. E. The mean, μX, is 2.
6. The Notion of parameter redundancy pertains to the situation when AR and MA characteristic polynomials φ(z) and share θ(z) share a common factor, in which case model may be simplified. Determine which of the following models are parameter redundant:
I. Xt = 21Xt−1 +Zt − 12Zt−1;
II. Xt = 12Xt−1 +Zt − 19Zt−2; III.Xt=−5Xt−1−1Xt−2+Zt+ 8Zt−1+ 1Zt−2.
The following problems are for students enrolled in PSTAT 274 ONLY

GE 1. Show that the two MA(1) processes
Xt =Zt+θZt−1,{Zt}∼WN(0,σ2),andYt =Z ̃t+θ1Z ̃t−1,{Z ̃t}∼WN(0,σ2θ2), where 0 < |θ| < 1, have the same autocovariance functions.
GE 2. You are given the following time series model: Xt = φXt−1 + Zt. Let Yt = X2t, that is, the original process observed only at even times. Show that Yt is also an AR(1) model Yt = φ∗Yt−1 + Zt∗ and determine φ∗ and Zt∗, that is, express φ∗ and Zt∗ via φ and Zt