---
title: "PSTAT 174/274, Spring 2023: Homework #4"
output: html_document
date: '2023-05-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note: In all problems, {Z~t~} ∼ WN(0,σ~Z~^2^ ) denotes white noise, and B denotes the backshift operator BX~t~ = X~t−1~.

### Question 1
For each of the models (1)-(3), write corresponding characteristic polynomials θ(z) and $\phi$(z). In other words, write models (1)-(3) as $\phi$(B)X~t~ = θ(B)Z~t~ and specify polynomials θ(z) and $\phi$(z). For each, identify the model as a certain (S)ARIMA model and determine whether the model in invertible and stationary:

(1) X~t~ = −0.2X~t−1~+Z~t~−2Z~t−1~; 
$$
\begin{aligned}
(1+ 0.2 B)X_t &= (1-2B)Z_t\\
\phi(z) &= 1 + 0.2z\\
\theta(z) &= 1-2z\\
&\text{SARIMA}\ (1,0,1) = ARMA(1,1)\\
\text{Because } |\theta| > 1, &\text{the model is not invertible.}\\
\text{Find roots of }\phi (z)&:\ 1-0.2z\ \rightarrow\ \ |z| = 5 > 1\\
&\text{The model is stationary}
\end{aligned}
$$)
\
(2) X~t~ = X~t−1~+Z~t~−0.2Z~t−1~−0.7Z~t−2~ 
$$
\begin{aligned}
(1-1B)X_t &= (1-0.2B-0.7B^2)Z_t\\
\phi(z) &= 1 - 1z\\
\theta(z) &= 1-0.2z-0.7z^2\\
&\text{SARIMA}\ (1,0,2) = ARMA(1,2)\\
\text{Because } |\phi| \geq  1,\ &\text{the model is not stationary.}\\
\text{Find roots of }\theta (z)&:\ 1-0.2z-0.7z^2\ \rightarrow\ \ |z| =  (1.060879+0i -1.346593+0i) > 1\\
&\text{The model is invertible.}
\end{aligned}
$$)
\

(3) X~t~ = X~t−3~+Z~t~+0.4Z~t−1~−0.45Z~t−2~.
$$
\begin{aligned}
(1-1B^3)X_t &= (1+0.4B-0.45B^2)Z_t\\
\phi(z) &= 1-1z^3\\
\theta(z) &= 1+0.z-0.45z^2\\
&\text{SARIMA}\ (3,0,2) = ARMA(3,2)\\
\text{Because } |\phi| \geq  1,\ &\text{the model is not stationary.}\\
\text{Find roots of }\theta (z)&:\ 1+0.4z-0.45z^2\ \rightarrow\ \ |-1.111111-0i  2.000000+0i| =  z > 1\\
&\text{The model is invertible.}
\end{aligned}
$$
\
2. Identify the model equation corresponding to SARIMA (0, 0, 2)(0, 0, 1)12 model. 

A. X~t~ = Z~t~ + θ~1~Z~t−1~ + θ~1~2Z~t−2~.
B. X~t~ = Z~t~ + θ~1~Z~t−1~ + θ~2~Z~t−2~ + θ~1~θ~2~Z~t−3~.
C. X~t~ = Z~t~ + θ~1~Z~t−1~ + θ~2~Z~t−2~ + θ~1~θ~2~Z~t−12~.
D. X~t~ = Z~t~ + θ~1~Z~t−2~ + θ~2~Z~t−12~ + θ~1~θ~2~Z~t−14~. 
E. X~t~ = Z~t~ + θ~1~Z~t−1~ + θ~2~Z~t−11~ + θ~1~θ~2~Z~t−12~.
$$
\text{SARIMA (0, 0, 2)(0, 0, 1)}_{12}:\\
X_t = (1+\theta_1B+\theta_2B_2)(1+\Theta_1B^{12})Z_t  \\
X_t=Z_t+\theta_1Z_{t-1} +\theta_2Z_{t-2}+\Theta_1Z_{t-12} + \theta_1\Theta_1Z_{t-13}+\theta_2\Theta_1Z_{t-13}
$$
\
The only option that matches is (D).
\

### Question 3
  (a) For the following SARIMA(p, d, q)×(P, D, Q)~s~ models, specify parameters p, d, q, P, D, Q and s, and write corresponding equations. It is OK to leave equations in the form.
$\phi$(B)$\Phi$(B~s~)(1−B)~d~(1−B~s~)~D~X~t~ = θ(B)$\Theta$(B~s~)Z~t~, Z~t~ ∼ WN(0,σ~Z~^2^).

|   (i) SARIMA(1, 1, 0) × (1, 1, 2)~6~, 
$$
(1-\Phi_1B^{12})(1-\theta_1B)(1-B)X_t=(1+\Theta_1B^{12}+\Theta_2B^{24})Z_t
$$
\
|   (ii) SARIMA(0, 1, 1) × (0, 0, 3)~12~, 
$$
(1-B)X_t=(1+\theta_1B)(1+\Theta_1B^{12}+\Theta_2B^{24}+\Theta_3B^{36})Z_t
$$
\
|   (iii) SARIMA(2, 1, 2) × (2, 0, 1)~4~. 
\
$$
(1-\theta_1B-\theta_2B^2)(1-B)(1-\Phi_1B^4-\Phi_2B^8)X_t=(1+\theta_1B+\theta_2B^2)(1+\Theta_1B^4)Z_t
$$
\
(b) For the following processes {X~t~}, identify SARIMA (p, d, q) × (P, D, Q)~s~ model:
|   (i) (1 − B~12~)~2~Xt = (1 − 0.3B)Zt; 
\
SARIMA(0,0,1)×(0,2,0)~12~
\
|   (ii) X~t~ = 0.5X~t−6~ + Z~t~; 
\
$$
X_t=0.5X_{t-6}+Z_t\\
(1-0.5B^6)X_t=Z_t
$$
SARIMA(0,0,0)×(1,0,0)~6~
\
|   (iii) (1 − 0.8B)(1 + 0.5B~4~)X~t~ = (1 − 1.5B)Z~t~.
\
SARIMA(1,0,1)×(1,0,0)~4~
\
(c) You are given a time series model where PACF is zero except for lags 12 and 24. Which model will have this
pattern?


mod2<-Arima(data,order=c(1, 0, 0), seasonal=list(order=c(2, 1, 0), period=12))
Acf <- ARMAacf(order(c(1,2,1)), seasonal(c(1,2,1)))
acf2AR(Acf)
Acf <- ARMAacf(order(c(1,2,1)))
ARMAacf(order = c(1,2,2), seasonal = c(1,2,2))
acf(Arima(rnorm(10000,.5,), order = c(1,2,2), seasonal = c(1,2,2)))
Z_t=rnorm(10000,0.5, 1.2)
sarima(Z_t, 1,1,1,1,1,1,12)
thepacf=ARMAacf(ar = c(1,.5,-.4), ma=c(),lag.max=30,pacf=T)
acf(theacf, plot=FALSE, lag.max = 30)
themodel = arima(Z_t, order = c(2,2,1), seasonal = list(order = c(2,1,1), period = 4))
acf(type=c("partial"), themodel$residuals, plot=FALSE)
acf(themodel$residuals, plot=FALSE)

(c) You are given a time series model where PACF is zero except for lags 12 and 24. Which model will have this
pattern?
4. For the processes Xt = 0.4Xt−1 + Zt − 0.7Zt−1,
(i) Simulate and plot 100 values of the processes;
(ii) Compute and graph their theoretical ACF and PACF using R.
(iii) Compute and graph their sample ACF and PACF using R. How do sample functions compare to their theoretical counterparts?
(iv) Analyze smoothness of the simulated processes using their ACF’s.
Please include the code with clear comments explaining the meaning of the code. Make sure to label the graphs.
The following problems are for students enrolled in PSTAT 274 ONLY
GE 1. Let {Yt} be the AR(1) plus noise time series defined by Yt = Xt +Wt, where {Wt} ∼ WN(0,σW2 ), {Xt} is theAR(1)processXt−φXt−1 =Zt,{Zt}∼WN(0,σZ2),|φ|<1,andE(WsZt)=0forallt,s.
(a) Show that {Yt} is stationary and find its autocovariance function.
(b) Show that the time series Ut := Yt − φYt−1 is 1-correlated (i.e., γU (h) = 0 for h > 1) and hence is MA(1) process.
(c) Conclude from (b) that {Yt} is an ARMA(1,1) process and express the three parameters of this model in terms ofφ,σW2 andσZ2.
GE 2. Find the ACVF, ACF and PACF for {Xt} when Xt = ΦXt−4 + Zt, |Φ| < 1.